# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-11-24 16:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tokenization', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Adp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('declension', models.CharField(blank=True, choices=[('nominative', 'Nominative'), ('dative', 'Dative'), ('ablative', 'Ablative'), ('instrumental', 'Instrumental'), ('locative', 'Locative')], max_length=20)),
                ('poss_number', models.CharField(blank=True, choices=[('singular', 'Sing'), ('plural', 'Plur')], max_length=10)),
                ('poss_person', models.CharField(blank=True, choices=[('1', '1'), ('2', '2'), ('3', '3')], max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Aux',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Cconj',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Det',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('definite', models.CharField(blank=True, choices=[('empty', 'Empty'), ('def', 'Definite'), ('indef', 'Indefinite')], max_length=8)),
                ('reflex', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Numeral',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_type', models.CharField(blank=True, choices=[('card', 'Card'), ('dist', 'Dist'), ('frac', 'Frac'), ('ord', 'Ord'), ('range', 'Range')], max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Part',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Pron',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.CharField(blank=True, choices=[('singular', 'Singular'), ('plural', 'Plural'), ('collective', 'Collective'), ('assocpl', 'Associative')], max_length=15)),
                ('declension', models.CharField(blank=True, choices=[('nominative', 'Nominative'), ('dative', 'Dative'), ('ablative', 'Ablative'), ('instrumental', 'Instrumental'), ('locative', 'Locative')], max_length=20)),
                ('pron_type', models.CharField(blank=True, choices=[('art', 'Art'), ('dem', 'Dem'), ('emp', 'Emp'), ('ind', 'Ind'), ('int', 'Int'), ('neg', 'Neg'), ('prs', 'Prs'), ('rcp', 'Rcp'), ('rel', 'Rel'), ('tot', 'Tot')], max_length=5)),
                ('reflex', models.BooleanField()),
                ('animacy', models.ManyToManyField(blank=True, to='tokenization.NounAnimacy')),
            ],
        ),
        migrations.CreateModel(
            name='Sconj',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='X',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.RemoveField(
            model_name='nounstate',
            name='parent',
        ),
        migrations.AddField(
            model_name='adv',
            name='degree',
            field=models.CharField(blank=True, choices=[('pos', 'Positive'), ('cmp', 'Comparative'), ('sup', 'Superlative')], max_length=5),
        ),
        migrations.AddField(
            model_name='noun',
            name='poss_number',
            field=models.CharField(blank=True, choices=[('singular', 'Sing'), ('plural', 'Plur')], max_length=10),
        ),
        migrations.AddField(
            model_name='noun',
            name='poss_person',
            field=models.CharField(blank=True, choices=[('1', '1'), ('2', '2'), ('3', '3')], max_length=10),
        ),
        migrations.AlterField(
            model_name='adj',
            name='degree',
            field=models.CharField(blank=True, choices=[('pos', 'Positive'), ('cmp', 'Comparative'), ('sup', 'Superlative')], max_length=5),
        ),
        migrations.AlterField(
            model_name='word',
            name='pos',
            field=models.CharField(blank=True, choices=[('noun', 'Noun'), ('verb', 'Verb'), ('punct', 'Punct'), ('sym', 'Sym'), ('x', 'X'), ('intj', 'Interjection'), ('adj', 'Adjective'), ('adv', 'Adverb'), ('det', 'Det'), ('sconj', 'Sconj'), ('cconj', 'Cconj'), ('num', 'Numeral'), ('particle', 'Part'), ('pronoun', 'Pron'), ('aux_verb', 'Aux'), ('adposition', 'Adp')], max_length=25),
        ),
        migrations.DeleteModel(
            name='NounState',
        ),
        migrations.AddField(
            model_name='x',
            name='parent',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='tokenization.Word'),
        ),
        migrations.AddField(
            model_name='sconj',
            name='parent',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='tokenization.Word'),
        ),
        migrations.AddField(
            model_name='pron',
            name='parent',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='tokenization.Word'),
        ),
        migrations.AddField(
            model_name='part',
            name='parent',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='tokenization.Word'),
        ),
        migrations.AddField(
            model_name='numeral',
            name='parent',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='tokenization.Word'),
        ),
        migrations.AddField(
            model_name='det',
            name='parent',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='tokenization.Word'),
        ),
        migrations.AddField(
            model_name='cconj',
            name='parent',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='tokenization.Word'),
        ),
        migrations.AddField(
            model_name='aux',
            name='parent',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='tokenization.Word'),
        ),
        migrations.AddField(
            model_name='adp',
            name='parent',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='tokenization.Word'),
        ),
    ]
