# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-06-25 20:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tokenization', '0002_token_sentence'),
    ]

    operations = [
        migrations.CreateModel(
            name='Word',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('update_date', models.DateTimeField(auto_now=True)),
                ('word', models.CharField(max_length=250)),
                ('declension_type', models.CharField(max_length=25)),
                ('declension', models.CharField(blank=True, choices=[('nominative', 'Nominative'), ('dative', 'Dative'), ('ablative', 'Ablative'), ('instrumental', 'Instrumental'), ('locative', 'Locative')], max_length=4)),
                ('quantity', models.CharField(blank=True, choices=[('singular', 'Singular'), ('plural', 'Plural')], max_length=10)),
                ('quantity_type', models.CharField(blank=True, choices=[('er', '-եր'), ('ner', '-ներ')], max_length=4)),
                ('form', models.CharField(max_length=250)),
            ],
        ),
    ]
