# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-11-25 17:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tokenization', '0002_auto_20171124_1649'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='det',
            name='reflex',
        ),
        migrations.RemoveField(
            model_name='pron',
            name='animacy',
        ),
        migrations.RemoveField(
            model_name='pron',
            name='quantity',
        ),
        migrations.AlterField(
            model_name='noun',
            name='poss_number',
            field=models.CharField(blank=True, choices=[('singular', 'Singular'), ('plural', 'Plural')], max_length=10),
        ),
        migrations.AlterField(
            model_name='word',
            name='pos',
            field=models.CharField(blank=True, choices=[('noun', 'Noun'), ('verb', 'Verb'), ('punct', 'Punct'), ('sym', 'Sym'), ('x', 'X'), ('intj', 'Interjection'), ('adj', 'Adjective'), ('adv', 'Adverb'), ('det', 'Det'), ('sconj', 'Sconj'), ('cconj', 'Cconj'), ('num', 'Numeral'), ('part', 'Part'), ('pron', 'Pron'), ('aux', 'Aux'), ('adp', 'Adp')], max_length=25),
        ),
    ]
