# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-11-28 19:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tokenization', '0003_auto_20171125_1758'),
    ]

    operations = [
        migrations.AddField(
            model_name='token',
            name='arc',
            field=models.IntegerField(blank=True, default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='token',
            name='arc_label',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
