# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-06-25 20:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tokenization', '0003_word'),
    ]

    operations = [
        migrations.AlterField(
            model_name='word',
            name='form',
            field=models.CharField(blank=True, choices=[('', 'None'), ('definite', 'Definite'), ('first', 'First'), ('second', 'Second')], max_length=10),
        ),
    ]
