# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-15 21:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tokenization', '0004_auto_20171128_1956'),
    ]

    operations = [
        migrations.AlterField(
            model_name='token',
            name='arc',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
