# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-15 21:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tokenization', '0005_auto_20171215_2127'),
    ]

    operations = [
        migrations.AddField(
            model_name='sconj',
            name='abbr',
            field=models.BooleanField(default=False),
        ),
    ]
