# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-06-26 15:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tokenization', '0005_auto_20170626_1900'),
    ]

    operations = [
        migrations.AlterField(
            model_name='word',
            name='declension',
            field=models.CharField(blank=True, choices=[('nominative', 'Nominative'), ('dative', 'Dative'), ('ablative', 'Ablative'), ('instrumental', 'Instrumental'), ('locative', 'Locative')], max_length=20),
        ),
    ]
