# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-15 21:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tokenization', '0007_cconj_abbr'),
    ]

    operations = [
        migrations.AddField(
            model_name='sconj',
            name='animacy',
            field=models.ManyToManyField(blank=True, to='tokenization.NounAnimacy'),
        ),
    ]
