# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-06-28 07:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tokenization', '0008_auto_20170628_1151'),
    ]

    operations = [
        migrations.AlterField(
            model_name='word',
            name='lemma',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='w_lemma', to='tokenization.Word'),
        ),
    ]
