# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-15 23:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tokenization', '0009_remove_sconj_animacy'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='adp',
            name='declension',
        ),
        migrations.RemoveField(
            model_name='pron',
            name='declension',
        ),
        migrations.RemoveField(
            model_name='pron',
            name='pron_type',
        ),
        migrations.AddField(
            model_name='adj',
            name='abbr',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='adj',
            name='echo',
            field=models.CharField(blank=True, choices=[('ech', 'Echo'), ('rdp', 'Reduplicative')], max_length=4),
        ),
        migrations.AddField(
            model_name='adj',
            name='foreign',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='adj',
            name='hyph',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='adj',
            name='name_type',
            field=models.CharField(blank=True, choices=[('com', 'Com'), ('geo', 'Geo'), ('giv', 'Giv'), ('oth', 'Oth'), ('pro', 'Pro'), ('prs', 'Prs'), ('sur', 'Sur')], max_length=4),
        ),
        migrations.AddField(
            model_name='adj',
            name='num_type',
            field=models.CharField(blank=True, choices=[('card', 'Card'), ('dist', 'Dist'), ('frac', 'Frac'), ('ord', 'Ord'), ('range', 'Range')], max_length=7),
        ),
        migrations.AddField(
            model_name='adj',
            name='poss',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='adj',
            name='verb_form',
            field=models.CharField(blank=True, choices=[('conv', 'Conv'), ('fin', 'Fin'), ('inf', 'Inf'), ('part', 'Part')], max_length=5),
        ),
        migrations.AddField(
            model_name='adj',
            name='voice',
            field=models.CharField(blank=True, choices=[('act', 'Act'), ('cau', 'Cau'), ('mid', 'Mid'), ('pass', 'Pass')], max_length=5),
        ),
        migrations.AddField(
            model_name='adp',
            name='abbr',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='adp',
            name='adp_type',
            field=models.CharField(blank=True, choices=[('prep', 'Prep'), ('post', 'Post'), ('comadp', 'Comadp')], max_length=7),
        ),
        migrations.AddField(
            model_name='adp',
            name='case',
            field=models.CharField(blank=True, choices=[('nominative', 'Nominative'), ('dative', 'Dative'), ('genitive', 'Genitive'), ('ablative', 'Ablative'), ('instrumental', 'Instrumental'), ('locative', 'Locative')], max_length=15),
        ),
        migrations.AddField(
            model_name='adp',
            name='echo',
            field=models.CharField(blank=True, choices=[('ech', 'Echo'), ('rdp', 'Reduplicative')], max_length=4),
        ),
        migrations.AddField(
            model_name='adp',
            name='foreign',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='adp',
            name='poss',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='adv',
            name='abbr',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='adv',
            name='echo',
            field=models.CharField(blank=True, choices=[('ech', 'Echo'), ('rdp', 'Reduplicative')], max_length=4),
        ),
        migrations.AddField(
            model_name='adv',
            name='foreign',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='adv',
            name='hyph',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='adv',
            name='name_type',
            field=models.CharField(blank=True, choices=[('com', 'Com'), ('geo', 'Geo'), ('giv', 'Giv'), ('oth', 'Oth'), ('pro', 'Pro'), ('prs', 'Prs'), ('sur', 'Sur')], max_length=4),
        ),
        migrations.AddField(
            model_name='adv',
            name='num_type',
            field=models.CharField(blank=True, choices=[('card', 'Card'), ('dist', 'Dist'), ('frac', 'Frac'), ('ord', 'Ord'), ('range', 'Range')], max_length=7),
        ),
        migrations.AddField(
            model_name='adv',
            name='poss',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='adv',
            name='pron_type',
            field=models.CharField(blank=True, choices=[('art', 'Art'), ('dem', 'Dem'), ('emp', 'Emp'), ('ind', 'Ind'), ('int', 'Int'), ('neg', 'Neg'), ('prs', 'Prs'), ('rcp', 'Rcp'), ('rel', 'Rel'), ('tot', 'Tot')], max_length=5),
        ),
        migrations.AddField(
            model_name='aux',
            name='abbr',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='aux',
            name='aspect',
            field=models.CharField(blank=True, choices=[('dur', 'Dur'), ('imp', 'Imp'), ('iter', 'Iter'), ('perf', 'Perf'), ('prosp', 'Prosp')], max_length=7),
        ),
        migrations.AddField(
            model_name='aux',
            name='echo',
            field=models.CharField(blank=True, choices=[('ech', 'Echo'), ('rdp', 'Reduplicative')], max_length=4),
        ),
        migrations.AddField(
            model_name='aux',
            name='foreign',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='aux',
            name='mood',
            field=models.CharField(blank=True, choices=[('cnd', 'Conditional'), ('imp', 'Imperative'), ('ind', 'Indicative'), ('nec', 'Necessitative'), ('sub', 'Subjunctive')], max_length=4),
        ),
        migrations.AddField(
            model_name='aux',
            name='number',
            field=models.CharField(blank=True, choices=[('singular', 'Singular'), ('plural', 'Plural'), ('collective', 'Collective'), ('assocpl', 'Associative')], max_length=7),
        ),
        migrations.AddField(
            model_name='aux',
            name='person',
            field=models.CharField(blank=True, choices=[('1', '1'), ('2', '2'), ('3', '3')], max_length=3),
        ),
        migrations.AddField(
            model_name='aux',
            name='polarity',
            field=models.CharField(blank=True, choices=[('neg', 'Neg'), ('pos', 'Pos')], max_length=4),
        ),
        migrations.AddField(
            model_name='aux',
            name='poss',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='aux',
            name='subcat',
            field=models.CharField(blank=True, choices=[('intr', 'Intransitive'), ('tran', 'Transitive')], max_length=5),
        ),
        migrations.AddField(
            model_name='aux',
            name='tense',
            field=models.CharField(blank=True, choices=[('imp', 'Imp'), ('past', 'Past'), ('pres', 'Pres')], max_length=5),
        ),
        migrations.AddField(
            model_name='aux',
            name='verb_form',
            field=models.CharField(blank=True, choices=[('conv', 'Conv'), ('fin', 'Fin'), ('inf', 'Inf'), ('part', 'Part')], max_length=5),
        ),
        migrations.AddField(
            model_name='aux',
            name='voice',
            field=models.CharField(blank=True, choices=[('act', 'Act'), ('cau', 'Cau'), ('mid', 'Mid'), ('pass', 'Pass')], max_length=5),
        ),
        migrations.AddField(
            model_name='cconj',
            name='conj_type',
            field=models.CharField(blank=True, choices=[('oper', 'Oper'), ('comp', 'Comp')], max_length=6),
        ),
        migrations.AddField(
            model_name='cconj',
            name='echo',
            field=models.CharField(blank=True, choices=[('ech', 'Echo'), ('rdp', 'Reduplicative')], max_length=4),
        ),
        migrations.AddField(
            model_name='cconj',
            name='foreign',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='cconj',
            name='poss',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='det',
            name='abbr',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='det',
            name='echo',
            field=models.CharField(blank=True, choices=[('ech', 'Echo'), ('rdp', 'Reduplicative')], max_length=4),
        ),
        migrations.AddField(
            model_name='det',
            name='foreign',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='det',
            name='person',
            field=models.CharField(blank=True, choices=[('1', '1'), ('2', '2'), ('3', '3')], max_length=3),
        ),
        migrations.AddField(
            model_name='det',
            name='poss',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='det',
            name='poss_number',
            field=models.CharField(blank=True, choices=[('sing', 'Sing'), ('plur', 'Plur')], max_length=5),
        ),
        migrations.AddField(
            model_name='det',
            name='poss_person',
            field=models.CharField(blank=True, choices=[('1', '1'), ('2', '2'), ('3', '3')], max_length=3),
        ),
        migrations.AddField(
            model_name='det',
            name='pron_type',
            field=models.CharField(blank=True, choices=[('art', 'Art'), ('dem', 'Dem'), ('emp', 'Emp'), ('ind', 'Ind'), ('int', 'Int'), ('neg', 'Neg'), ('prs', 'Prs'), ('rcp', 'Rcp'), ('rel', 'Rel'), ('tot', 'Tot')], max_length=5),
        ),
        migrations.AddField(
            model_name='det',
            name='reflex',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='intj',
            name='abbr',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='intj',
            name='echo',
            field=models.CharField(blank=True, choices=[('ech', 'Echo'), ('rdp', 'Reduplicative')], max_length=4),
        ),
        migrations.AddField(
            model_name='intj',
            name='foreign',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='intj',
            name='poss',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='numeral',
            name='abbr',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='numeral',
            name='echo',
            field=models.CharField(blank=True, choices=[('ech', 'Echo'), ('rdp', 'Reduplicative')], max_length=4),
        ),
        migrations.AddField(
            model_name='numeral',
            name='foreign',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='numeral',
            name='num_form',
            field=models.CharField(blank=True, choices=[('armenian', 'Armenian'), ('digit', 'Digit'), ('roman', 'Roman'), ('word', 'Word')], max_length=10),
        ),
        migrations.AddField(
            model_name='numeral',
            name='poss',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='part',
            name='abbr',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='part',
            name='echo',
            field=models.CharField(blank=True, choices=[('ech', 'Echo'), ('rdp', 'Reduplicative')], max_length=4),
        ),
        migrations.AddField(
            model_name='part',
            name='foreign',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='part',
            name='mood',
            field=models.CharField(blank=True, choices=[('cnd', 'Conditional'), ('imp', 'Imperative'), ('ind', 'Indicative'), ('nec', 'Necessitative'), ('sub', 'Subjunctive')], max_length=4),
        ),
        migrations.AddField(
            model_name='part',
            name='poss',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='pron',
            name='abbr',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='pron',
            name='animacy',
            field=models.ManyToManyField(blank=True, to='tokenization.NounAnimacy'),
        ),
        migrations.AddField(
            model_name='pron',
            name='case',
            field=models.CharField(blank=True, choices=[('nominative', 'Nominative'), ('dative', 'Dative'), ('genitive', 'Genitive'), ('ablative', 'Ablative'), ('instrumental', 'Instrumental'), ('locative', 'Locative')], max_length=15),
        ),
        migrations.AddField(
            model_name='pron',
            name='echo',
            field=models.CharField(blank=True, choices=[('ech', 'Echo'), ('rdp', 'Reduplicative')], max_length=4),
        ),
        migrations.AddField(
            model_name='pron',
            name='foreign',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='pron',
            name='number',
            field=models.CharField(blank=True, choices=[('singular', 'Singular'), ('plural', 'Plural'), ('collective', 'Collective'), ('assocpl', 'Associative')], max_length=7),
        ),
        migrations.AddField(
            model_name='pron',
            name='person',
            field=models.CharField(blank=True, choices=[('1', '1'), ('2', '2'), ('3', '3')], max_length=3),
        ),
        migrations.AddField(
            model_name='pron',
            name='poss',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='pron',
            name='poss_number',
            field=models.CharField(blank=True, choices=[('sing', 'Sing'), ('plur', 'Plur')], max_length=5),
        ),
        migrations.AddField(
            model_name='pron',
            name='poss_person',
            field=models.CharField(blank=True, choices=[('1', '1'), ('2', '2'), ('3', '3')], max_length=3),
        ),
        migrations.AddField(
            model_name='sconj',
            name='echo',
            field=models.CharField(blank=True, choices=[('ech', 'Echo'), ('rdp', 'Reduplicative')], max_length=4),
        ),
        migrations.AddField(
            model_name='sconj',
            name='foreign',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='sconj',
            name='poss',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='x',
            name='foreign',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='adj',
            name='degree',
            field=models.CharField(blank=True, choices=[('pos', 'Positive'), ('cmp', 'Comparative'), ('sup', 'Superlative')], max_length=4),
        ),
        migrations.AlterField(
            model_name='adp',
            name='poss_number',
            field=models.CharField(blank=True, choices=[('sing', 'Sing'), ('plur', 'Plur')], max_length=5),
        ),
        migrations.AlterField(
            model_name='adp',
            name='poss_person',
            field=models.CharField(blank=True, choices=[('1', '1'), ('2', '2'), ('3', '3')], max_length=3),
        ),
        migrations.AlterField(
            model_name='adv',
            name='degree',
            field=models.CharField(blank=True, choices=[('pos', 'Positive'), ('cmp', 'Comparative'), ('sup', 'Superlative')], max_length=4),
        ),
        migrations.AlterField(
            model_name='det',
            name='definite',
            field=models.CharField(blank=True, choices=[('def', 'Def'), ('indef', 'Indef')], max_length=6),
        ),
        migrations.AlterField(
            model_name='numeral',
            name='num_type',
            field=models.CharField(blank=True, choices=[('card', 'Card'), ('dist', 'Dist'), ('frac', 'Frac'), ('ord', 'Ord'), ('range', 'Range')], max_length=7),
        ),
        migrations.AlterField(
            model_name='pron',
            name='reflex',
            field=models.BooleanField(default=False),
        ),
    ]
