# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-06-28 07:53
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tokenization', '0010_remove_word_lemma'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='word',
            name='pos',
        ),
    ]
