# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-16 22:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tokenization', '0010_auto_20171215_2304'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adj',
            name='parent',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tokenization.Word'),
        ),
    ]
