# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-06-28 07:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tokenization', '0011_remove_word_pos'),
    ]

    operations = [
        migrations.AddField(
            model_name='word',
            name='lemma',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='w_lemma', to='tokenization.Word'),
        ),
        migrations.AddField(
            model_name='word',
            name='pos',
            field=models.CharField(blank=True, choices=[('noun', 'Noun')], max_length=25),
        ),
    ]
