# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-17 00:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tokenization', '0011_auto_20171216_2234'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adp',
            name='parent',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tokenization.Word'),
        ),
        migrations.AlterField(
            model_name='adv',
            name='parent',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tokenization.Word'),
        ),
        migrations.AlterField(
            model_name='aux',
            name='parent',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tokenization.Word'),
        ),
        migrations.AlterField(
            model_name='cconj',
            name='parent',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tokenization.Word'),
        ),
        migrations.AlterField(
            model_name='det',
            name='parent',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tokenization.Word'),
        ),
        migrations.AlterField(
            model_name='intj',
            name='parent',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tokenization.Word'),
        ),
        migrations.AlterField(
            model_name='numeral',
            name='parent',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tokenization.Word'),
        ),
        migrations.AlterField(
            model_name='part',
            name='parent',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tokenization.Word'),
        ),
        migrations.AlterField(
            model_name='pron',
            name='parent',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tokenization.Word'),
        ),
        migrations.AlterField(
            model_name='punct',
            name='parent',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tokenization.Word'),
        ),
        migrations.AlterField(
            model_name='sconj',
            name='parent',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tokenization.Word'),
        ),
        migrations.AlterField(
            model_name='sym',
            name='parent',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tokenization.Word'),
        ),
        migrations.AlterField(
            model_name='x',
            name='parent',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tokenization.Word'),
        ),
    ]
