# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-17 19:21
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tokenization', '0012_auto_20171217_0002'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='noun',
            name='animacy',
        ),
        migrations.RemoveField(
            model_name='noun',
            name='declension',
        ),
        migrations.RemoveField(
            model_name='noun',
            name='declension_type',
        ),
        migrations.RemoveField(
            model_name='noun',
            name='definite',
        ),
        migrations.RemoveField(
            model_name='noun',
            name='materiality',
        ),
        migrations.RemoveField(
            model_name='noun',
            name='nominalized',
        ),
        migrations.RemoveField(
            model_name='noun',
            name='oblique_stem',
        ),
        migrations.RemoveField(
            model_name='noun',
            name='parent',
        ),
        migrations.RemoveField(
            model_name='noun',
            name='poss_number',
        ),
        migrations.RemoveField(
            model_name='noun',
            name='poss_person',
        ),
        migrations.RemoveField(
            model_name='noun',
            name='proper',
        ),
        migrations.RemoveField(
            model_name='noun',
            name='quantity',
        ),
        migrations.RemoveField(
            model_name='noun',
            name='quantity_type',
        ),
        migrations.RemoveField(
            model_name='noun',
            name='singular_stem',
        ),
    ]
