# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-06-28 08:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tokenization', '0012_auto_20170628_1155'),
    ]

    operations = [
        migrations.CreateModel(
            name='Noun',
            fields=[
                ('parent', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='w_parent', serialize=False, to='tokenization.Word')),
                ('declension_type', models.CharField(max_length=25)),
                ('declension', models.CharField(blank=True, choices=[('nominative', 'Nominative'), ('dative', 'Dative'), ('ablative', 'Ablative'), ('instrumental', 'Instrumental'), ('locative', 'Locative')], max_length=20)),
                ('quantity', models.CharField(blank=True, choices=[('singular', 'Singular'), ('plural', 'Plural')], max_length=10)),
                ('quantity_type', models.CharField(blank=True, choices=[('եր', '-եր'), ('ներ', '-ներ')], max_length=10)),
                ('form', models.CharField(blank=True, choices=[('', 'None'), ('definite', 'Definite'), ('first', 'First'), ('second', 'Second')], max_length=10)),
            ],
            bases=('tokenization.word',),
        ),
        migrations.RemoveField(
            model_name='word',
            name='declension',
        ),
        migrations.RemoveField(
            model_name='word',
            name='declension_type',
        ),
        migrations.RemoveField(
            model_name='word',
            name='form',
        ),
        migrations.RemoveField(
            model_name='word',
            name='quantity',
        ),
        migrations.RemoveField(
            model_name='word',
            name='quantity_type',
        ),
    ]
