# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-17 19:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tokenization', '0013_auto_20171217_1921'),
    ]

    operations = [
        migrations.AddField(
            model_name='noun',
            name='animacy',
            field=models.ManyToManyField(blank=True, related_name='n_animacy', to='tokenization.NounAnimacy'),
        ),
        migrations.AddField(
            model_name='noun',
            name='case',
            field=models.CharField(blank=True, choices=[('nominative', 'Nominative'), ('dative', 'Dative'), ('genitive', 'Genitive'), ('ablative', 'Ablative'), ('instrumental', 'Instrumental'), ('locative', 'Locative')], max_length=15),
        ),
        migrations.AddField(
            model_name='noun',
            name='definite',
            field=models.CharField(blank=True, choices=[('def', 'Def'), ('indef', 'Indef')], max_length=6),
        ),
        migrations.AddField(
            model_name='noun',
            name='materiality',
            field=models.CharField(blank=True, choices=[('conc', 'concrete'), ('astr', 'abstract')], max_length=5),
        ),
        migrations.AddField(
            model_name='noun',
            name='name_type',
            field=models.CharField(blank=True, choices=[('com', 'Com'), ('geo', 'Geo'), ('giv', 'Giv'), ('oth', 'Oth'), ('pro', 'Pro'), ('prs', 'Prs'), ('sur', 'Sur')], max_length=4),
        ),
        migrations.AddField(
            model_name='noun',
            name='nominalized',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='noun',
            name='number',
            field=models.CharField(blank=True, choices=[('singular', 'Singular'), ('plural', 'Plural'), ('collective', 'Collective'), ('assocpl', 'Associative')], max_length=7),
        ),
        migrations.AddField(
            model_name='noun',
            name='parent',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='n_parent', to='tokenization.Word'),
        ),
        migrations.AddField(
            model_name='noun',
            name='poss_number',
            field=models.CharField(blank=True, choices=[('sing', 'Sing'), ('plur', 'Plur')], max_length=5),
        ),
        migrations.AddField(
            model_name='noun',
            name='poss_person',
            field=models.CharField(blank=True, choices=[('1', '1'), ('2', '2'), ('3', '3')], max_length=3),
        ),
        migrations.AddField(
            model_name='noun',
            name='verb_form',
            field=models.CharField(blank=True, choices=[('conv', 'Conv'), ('fin', 'Fin'), ('inf', 'Inf'), ('part', 'Part')], max_length=5),
        ),
    ]
