# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-17 21:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tokenization', '0014_auto_20171217_1928'),
    ]

    operations = [
        migrations.AddField(
            model_name='noun',
            name='proper',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
