# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-06-28 08:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tokenization', '0014_auto_20170628_1206'),
    ]

    operations = [
        migrations.CreateModel(
            name='Noun',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('declension_type', models.CharField(max_length=25)),
                ('declension', models.CharField(blank=True, choices=[('nominative', 'Nominative'), ('dative', 'Dative'), ('ablative', 'Ablative'), ('instrumental', 'Instrumental'), ('locative', 'Locative')], max_length=20)),
                ('quantity', models.CharField(blank=True, choices=[('singular', 'Singular'), ('plural', 'Plural')], max_length=10)),
                ('quantity_type', models.CharField(blank=True, choices=[('եր', '-եր'), ('ներ', '-ներ')], max_length=10)),
                ('form', models.CharField(blank=True, choices=[('', 'None'), ('definite', 'Definite'), ('first', 'First'), ('second', 'Second')], max_length=10)),
                ('parent', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='w_parent', to='tokenization.Word')),
            ],
        ),
    ]
