# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-06-28 08:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tokenization', '0015_noun'),
    ]

    operations = [
        migrations.AlterField(
            model_name='noun',
            name='declension_type',
            field=models.CharField(max_length=25, null=True),
        ),
    ]
