# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-17 21:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tokenization', '0015_noun_proper'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aux',
            name='number',
            field=models.CharField(blank=True, choices=[('singular', 'Singular'), ('plural', 'Plural'), ('collective', 'Collective'), ('assocpl', 'Associative')], max_length=13),
        ),
        migrations.AlterField(
            model_name='noun',
            name='number',
            field=models.CharField(blank=True, choices=[('singular', 'Singular'), ('plural', 'Plural'), ('collective', 'Collective'), ('assocpl', 'Associative')], max_length=13),
        ),
        migrations.AlterField(
            model_name='noun',
            name='proper',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='pron',
            name='number',
            field=models.CharField(blank=True, choices=[('singular', 'Singular'), ('plural', 'Plural'), ('collective', 'Collective'), ('assocpl', 'Associative')], max_length=13),
        ),
    ]
