# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-06-28 08:29
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tokenization', '0017_auto_20170628_1227'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='noun',
            name='parent',
        ),
        migrations.RemoveField(
            model_name='word',
            name='lemma',
        ),
        migrations.DeleteModel(
            name='Noun',
        ),
        migrations.DeleteModel(
            name='Word',
        ),
    ]
