# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-27 18:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tokenization', '0017_auto_20171227_1540'),
    ]

    operations = [
        migrations.AlterField(
            model_name='verb',
            name='parent',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='v_parent', to='tokenization.Word'),
        ),
    ]
