# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-06-28 16:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tokenization', '0019_auto_20170628_1229'),
    ]

    operations = [
        migrations.AddField(
            model_name='token',
            name='tag',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tokenization.Word'),
        ),
    ]
