# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-19 00:48
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tokenization', '0020_auto_20180119_0047'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='verb',
            name='voice',
        ),
    ]
