# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-07-07 17:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tokenization', '0020_token_tag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='noun',
            name='parent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='w_parent', to='tokenization.Word'),
        ),
        migrations.AlterField(
            model_name='word',
            name='pos',
            field=models.CharField(blank=True, choices=[('noun', 'Noun'), ('verb', 'Verb')], max_length=25),
        ),
    ]
