# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-07-07 17:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tokenization', '0021_auto_20170707_2141'),
    ]

    operations = [
        migrations.CreateModel(
            name='Verb',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('root', models.CharField(blank=True, max_length=250)),
                ('conj', models.CharField(blank=True, max_length=250)),
                ('form', models.CharField(blank=True, max_length=250)),
                ('type', models.CharField(blank=True, max_length=250)),
                ('quantity', models.CharField(blank=True, choices=[(1, 'Singular'), (2, 'Plural')], max_length=10)),
                ('demq', models.CharField(blank=True, choices=[(1, 'First'), (2, 'Second'), (3, 'Third')], max_length=3)),
                ('parent', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='v_parent', to='tokenization.Word')),
            ],
        ),
        migrations.AlterField(
            model_name='noun',
            name='parent',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='w_parent', to='tokenization.Word'),
        ),
    ]
