# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-07-07 17:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tokenization', '0022_auto_20170707_2143'),
    ]

    operations = [
        migrations.AlterField(
            model_name='noun',
            name='parent',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='n_parent', to='tokenization.Word'),
        ),
    ]
