# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-20 10:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tokenization', '0023_auto_20180119_0049'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adj',
            name='degree',
            field=models.CharField(blank=True, choices=[('pos', 'Positive'), ('cmp', 'Comparative'), ('sup', 'Superlative'), ('abs', 'Absolute superlative')], max_length=4),
        ),
        migrations.AlterField(
            model_name='adv',
            name='degree',
            field=models.CharField(blank=True, choices=[('pos', 'Positive'), ('cmp', 'Comparative'), ('sup', 'Superlative'), ('abs', 'Absolute superlative')], max_length=4),
        ),
        migrations.AlterField(
            model_name='verb',
            name='voice',
            field=models.CharField(choices=[('middle', 'ՉԲ'), ('active', 'ՆԲ')], default='middle', max_length=8),
        ),
    ]
