# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-07-07 17:50
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tokenization', '0023_auto_20170707_2143'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='verb',
            name='conj',
        ),
    ]
