# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-07-13 13:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tokenization', '0024_remove_verb_conj'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='token',
            name='tag',
        ),
        migrations.AddField(
            model_name='token',
            name='tag',
            field=models.ManyToManyField(blank=True, null=True, to='tokenization.Word'),
        ),
    ]
