# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-23 15:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tokenization', '0024_auto_20180120_1048'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='word',
            name='lemma',
        ),
        migrations.AddField(
            model_name='adj',
            name='lemma',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='adp',
            name='lemma',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='adv',
            name='lemma',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='aux',
            name='lemma',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='cconj',
            name='lemma',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='det',
            name='lemma',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='intj',
            name='lemma',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='noun',
            name='lemma',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='numeral',
            name='lemma',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='part',
            name='lemma',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='pron',
            name='lemma',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='punct',
            name='lemma',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='sconj',
            name='lemma',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='sym',
            name='lemma',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='verb',
            name='lemma',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='x',
            name='lemma',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='adj',
            name='parent',
            field=models.OneToOneField(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, to='tokenization.Word'),
        ),
        migrations.AlterField(
            model_name='adp',
            name='parent',
            field=models.OneToOneField(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, to='tokenization.Word'),
        ),
        migrations.AlterField(
            model_name='adv',
            name='parent',
            field=models.OneToOneField(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, to='tokenization.Word'),
        ),
        migrations.AlterField(
            model_name='aux',
            name='parent',
            field=models.OneToOneField(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, to='tokenization.Word'),
        ),
        migrations.AlterField(
            model_name='cconj',
            name='parent',
            field=models.OneToOneField(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, to='tokenization.Word'),
        ),
        migrations.AlterField(
            model_name='det',
            name='parent',
            field=models.OneToOneField(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, to='tokenization.Word'),
        ),
        migrations.AlterField(
            model_name='intj',
            name='parent',
            field=models.OneToOneField(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, to='tokenization.Word'),
        ),
        migrations.AlterField(
            model_name='noun',
            name='parent',
            field=models.OneToOneField(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='n_parent', to='tokenization.Word'),
        ),
        migrations.AlterField(
            model_name='numeral',
            name='parent',
            field=models.OneToOneField(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, to='tokenization.Word'),
        ),
        migrations.AlterField(
            model_name='part',
            name='parent',
            field=models.OneToOneField(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, to='tokenization.Word'),
        ),
        migrations.AlterField(
            model_name='pron',
            name='parent',
            field=models.OneToOneField(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, to='tokenization.Word'),
        ),
        migrations.AlterField(
            model_name='punct',
            name='parent',
            field=models.OneToOneField(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, to='tokenization.Word'),
        ),
        migrations.AlterField(
            model_name='sconj',
            name='parent',
            field=models.OneToOneField(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, to='tokenization.Word'),
        ),
        migrations.AlterField(
            model_name='sym',
            name='parent',
            field=models.OneToOneField(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, to='tokenization.Word'),
        ),
        migrations.AlterField(
            model_name='verb',
            name='parent',
            field=models.OneToOneField(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='v_parent', to='tokenization.Word'),
        ),
        migrations.AlterField(
            model_name='x',
            name='parent',
            field=models.OneToOneField(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, to='tokenization.Word'),
        ),
    ]
