# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-23 18:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tokenization', '0025_auto_20180123_1518'),
    ]

    operations = [
        migrations.AddField(
            model_name='token',
            name='trim_spaceafter',
            field=models.BooleanField(default=False),
        ),
    ]
