# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-07-13 16:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tokenization', '0025_auto_20170713_1702'),
    ]

    operations = [
        migrations.AddField(
            model_name='token',
            name='checked',
            field=models.BooleanField(default=False),
        ),
    ]
