# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-07-22 10:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tokenization', '0026_token_checked'),
    ]

    operations = [
        migrations.AddField(
            model_name='verb',
            name='ending',
            field=models.CharField(blank=True, max_length=250),
        ),
    ]
