# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-23 19:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tokenization', '0026_token_trim_spaceafter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adp',
            name='case',
            field=models.CharField(blank=True, choices=[('nom', 'Nominative'), ('dat', 'Dative'), ('gen', 'Genitive'), ('abl', 'Ablative'), ('ins', 'Instrumental'), ('loc', 'Locative')], max_length=15),
        ),
        migrations.AlterField(
            model_name='aux',
            name='number',
            field=models.CharField(blank=True, choices=[('sing', 'Singular'), ('plur', 'Plural'), ('coll', 'Collective'), ('assoc', 'Associative')], max_length=13),
        ),
        migrations.AlterField(
            model_name='noun',
            name='case',
            field=models.CharField(blank=True, choices=[('nom', 'Nominative'), ('dat', 'Dative'), ('gen', 'Genitive'), ('abl', 'Ablative'), ('ins', 'Instrumental'), ('loc', 'Locative')], max_length=15),
        ),
        migrations.AlterField(
            model_name='noun',
            name='number',
            field=models.CharField(blank=True, choices=[('sing', 'Singular'), ('plur', 'Plural'), ('coll', 'Collective'), ('assoc', 'Associative')], max_length=13),
        ),
        migrations.AlterField(
            model_name='pron',
            name='case',
            field=models.CharField(blank=True, choices=[('nom', 'Nominative'), ('dat', 'Dative'), ('gen', 'Genitive'), ('abl', 'Ablative'), ('ins', 'Instrumental'), ('loc', 'Locative')], max_length=15),
        ),
        migrations.AlterField(
            model_name='pron',
            name='number',
            field=models.CharField(blank=True, choices=[('sing', 'Singular'), ('plur', 'Plural'), ('coll', 'Collective'), ('assoc', 'Associative')], max_length=13),
        ),
        migrations.AlterField(
            model_name='verb',
            name='number',
            field=models.CharField(blank=True, choices=[('sing', 'Singular'), ('plur', 'Plural'), ('coll', 'Collective'), ('assoc', 'Associative')], max_length=13),
        ),
    ]
