# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-26 14:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tokenization', '0027_auto_20180123_1923'),
    ]

    operations = [
        migrations.AddField(
            model_name='noun',
            name='abbr',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='noun',
            name='echo',
            field=models.CharField(blank=True, choices=[('ech', 'Echo'), ('rdp', 'Reduplicative')], max_length=4),
        ),
        migrations.AddField(
            model_name='noun',
            name='foreign',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='noun',
            name='poss',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='punct',
            name='abbr',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='punct',
            name='echo',
            field=models.CharField(blank=True, choices=[('ech', 'Echo'), ('rdp', 'Reduplicative')], max_length=4),
        ),
        migrations.AddField(
            model_name='punct',
            name='foreign',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='punct',
            name='poss',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='sym',
            name='abbr',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='sym',
            name='echo',
            field=models.CharField(blank=True, choices=[('ech', 'Echo'), ('rdp', 'Reduplicative')], max_length=4),
        ),
        migrations.AddField(
            model_name='sym',
            name='foreign',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='sym',
            name='poss',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='verb',
            name='abbr',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='verb',
            name='echo',
            field=models.CharField(blank=True, choices=[('ech', 'Echo'), ('rdp', 'Reduplicative')], max_length=4),
        ),
        migrations.AddField(
            model_name='verb',
            name='foreign',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='verb',
            name='poss',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='x',
            name='abbr',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='x',
            name='echo',
            field=models.CharField(blank=True, choices=[('ech', 'Echo'), ('rdp', 'Reduplicative')], max_length=4),
        ),
        migrations.AddField(
            model_name='x',
            name='poss',
            field=models.BooleanField(default=False),
        ),
    ]
