# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-11-03 17:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('update_date', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=250)),
                ('patronymic', models.CharField(blank=True, max_length=250, null=True)),
                ('pseudonym', models.CharField(blank=True, max_length=250, null=True)),
                ('birth_date', models.CharField(max_length=15)),
                ('death_date', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Bibliography',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('update_date', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=650)),
                ('tokens_count', models.IntegerField(default=0)),
                ('license', models.CharField(choices=[('private', 'Պաշտպանված է հեղինակային իրավունքով'), ('public', 'Հանրային սեփականություն')], default='public', max_length=20)),
                ('tokenized', models.CharField(choices=[('no', 'Թոքենիզացված չէ'), ('yes', 'Թոքենիզացված է'), ('validated', 'Թոքենիզացված է, ստուգված է')], default='no', max_length=20)),
                ('tagged', models.CharField(choices=[('no', 'Թագավորված չէ'), ('yes', 'Թագավորված է'), ('validated', 'Թագավորված է, ստուգված է')], default='no', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Text',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('update_date', models.DateTimeField(auto_now=True)),
                ('text_name', models.CharField(blank=True, max_length=400, null=True)),
                ('text', models.TextField()),
                ('language', models.CharField(choices=[('eastern', 'Արևելահայերեն'), ('western', 'Արևմտահայերեն'), ('middle', 'Միջին հայերեն'), ('grabar', 'Գրաբար')], default='eastern', max_length=20)),
                ('dialect', models.CharField(choices=[('literary', 'Գրական'), ('dialect', 'Բարբառային')], default='literary', max_length=20)),
                ('spelling', models.CharField(choices=[('modern_current', 'Արդի (1940-ներկա)'), ('modern_old', 'Արդի (1922-1940)'), ('classic', 'Դասական')], default='modern_current', max_length=20)),
                ('ev_letter', models.CharField(choices=[('1', 'եւ'), ('2', 'և')], default='1', max_length=2)),
                ('author', models.ManyToManyField(blank=True, to='bibliography.Author')),
            ],
        ),
        migrations.CreateModel(
            name='Fiction',
            fields=[
                ('bibliography_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='bibliography.Bibliography')),
                ('genre', models.CharField(max_length=100)),
                ('text_creation_date', models.CharField(max_length=15)),
                ('text_publication_date', models.CharField(max_length=15)),
                ('mediation', models.CharField(choices=[('yes', 'Միջնորդված'), ('no', 'Չմիջնորդված')], default='no', max_length=4)),
                ('translation_original', models.CharField(choices=[('no', 'Դատարկ'), ('eng', 'Անգլերեն'), ('ru', 'Ռուսերեն'), ('ge', 'Գերմաներեն'), ('esp', 'Իսպաներեն'), ('fr', 'Ֆրանսերեն')], default='no', max_length=10)),
                ('translation_mediator', models.CharField(choices=[('no', 'Դատարկ'), ('eng', 'Անգլերեն'), ('ru', 'Ռուսերեն'), ('ge', 'Գերմաներեն'), ('esp', 'Իսպաներեն'), ('fr', 'Ֆրանսերեն')], default='no', max_length=10)),
                ('text', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bibliography.Text')),
                ('translation', models.ManyToManyField(blank=True, to='bibliography.Author')),
            ],
            bases=('bibliography.bibliography',),
        ),
        migrations.CreateModel(
            name='Press',
            fields=[
                ('bibliography_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='bibliography.Bibliography')),
                ('text_publication_date', models.CharField(max_length=15)),
                ('number', models.IntegerField(blank=True, default=0, null=True)),
                ('sphere', models.CharField(max_length=200)),
                ('type', models.CharField(max_length=200)),
                ('link', models.CharField(blank=True, max_length=200, null=True)),
                ('text', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bibliography.Text')),
            ],
            bases=('bibliography.bibliography',),
        ),
        migrations.CreateModel(
            name='Textbook',
            fields=[
                ('bibliography_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='bibliography.Bibliography')),
                ('text_creation_date', models.CharField(max_length=15)),
                ('text_publication_date', models.CharField(max_length=15)),
                ('sphere', models.CharField(choices=[('morphology', 'Ձևաբանություն'), ('syntax', 'Շարահյուսություն'), ('lexicology', 'Բառագիտություն'), ('linguistics', 'Տեսական լեզվաբանություն')], default='linguistics', max_length=25)),
                ('author', models.ManyToManyField(to='bibliography.Author')),
                ('texts', models.ManyToManyField(to='bibliography.Text')),
            ],
            bases=('bibliography.bibliography',),
        ),
        migrations.AddField(
            model_name='bibliography',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.UserProfile'),
        ),
    ]
