# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-22 14:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('update_date', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(blank=True, max_length=250)),
                ('birth_date', models.DateField(blank=True)),
                ('death_date', models.DateField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Bibliography',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('update_date', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=650)),
                ('tokens_count', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Text',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('update_date', models.DateTimeField(auto_now=True)),
                ('text', models.TextField()),
                ('language', models.CharField(choices=[('eastern', 'Արևելահայերեն'), ('western', 'Արևմտահայերեն'), ('middle', 'Միջին հայերեն'), ('grabar', 'Գրաբար')], default='eastern', max_length=20)),
                ('dialect', models.CharField(choices=[('literary', 'Գրական'), ('dialect', 'Բարբառային')], default='literary', max_length=20)),
                ('spelling', models.CharField(choices=[('modern_old', 'Արդի (1922-1940)'), ('modern_current', 'Արդի (1940-)'), ('classic', 'Դասական')], default='modern_current', max_length=20)),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='bibliography.Author')),
            ],
        ),
        migrations.CreateModel(
            name='Fiction',
            fields=[
                ('bibliography_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='bibliography.Bibliography')),
                ('genre', models.CharField(max_length=100)),
                ('text_creation_date', models.DateField(blank=True)),
                ('text_publication_date', models.DateField(blank=True)),
                ('mediation', models.CharField(choices=[('yes', 'Միջնորդված'), ('no', 'Չմիջնորդված')], default='no', max_length=4)),
                ('translation_original', models.CharField(choices=[('no', 'Դատարկ'), ('eng', 'Անգլերեն'), ('ru', 'Ռուսերեն'), ('ge', 'Գերմաներեն'), ('esp', 'Իսպաներեն'), ('fr', 'Ֆրանսերեն')], default='no', max_length=10)),
                ('translation_mediator', models.CharField(choices=[('no', 'Դատարկ'), ('eng', 'Անգլերեն'), ('ru', 'Ռուսերեն'), ('ge', 'Գերմաներեն'), ('esp', 'Իսպաներեն'), ('fr', 'Ֆրանսերեն')], default='no', max_length=10)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bibliography.Author')),
                ('text', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bibliography.Text')),
            ],
            bases=('bibliography.bibliography',),
        ),
        migrations.CreateModel(
            name='Press',
            fields=[
                ('bibliography_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='bibliography.Bibliography')),
                ('text_publication_date', models.DateField(blank=True)),
                ('number', models.IntegerField(default=0)),
                ('sphere', models.CharField(max_length=200)),
                ('type', models.CharField(max_length=200)),
                ('author', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='bibliography.Author')),
                ('text', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bibliography.Text')),
            ],
            bases=('bibliography.bibliography',),
        ),
        migrations.CreateModel(
            name='Textbook',
            fields=[
                ('bibliography_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='bibliography.Bibliography')),
                ('sphere', models.CharField(max_length=150)),
                ('text_creation_date', models.DateField(blank=True)),
                ('text_publication_date', models.DateField(blank=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bibliography.Author')),
                ('texts', models.ManyToManyField(to='bibliography.Text')),
            ],
            bases=('bibliography.bibliography',),
        ),
    ]
