# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-22 14:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bibliography', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='textbook',
            name='sphere',
            field=models.CharField(choices=[('morphology', 'Ձևաբանություն'), ('syntax', 'Շարահյուսություն'), ('lexicology', 'Բառագիտություն'), ('linguistics', 'Տեսական լեզվաբանություն')], default='linguistics', max_length=25),
        ),
    ]
