# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-23 17:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bibliography', '0003_auto_20170223_0142'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='name',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='fiction',
            name='text_creation_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='fiction',
            name='text_publication_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='press',
            name='text_publication_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='text',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='bibliography.Author'),
        ),
        migrations.AlterField(
            model_name='textbook',
            name='text_creation_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='textbook',
            name='text_publication_date',
            field=models.DateField(),
        ),
    ]
