# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-23 18:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
        ('bibliography', '0004_auto_20170223_2138'),
    ]

    operations = [
        migrations.AddField(
            model_name='bibliography',
            name='profile',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='user.UserProfile'),
            preserve_default=False,
        ),
    ]
