# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-23 19:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bibliography', '0006_auto_20170223_2321'),
    ]

    operations = [
        migrations.AlterField(
            model_name='textbook',
            name='author',
            field=models.ForeignKey(default=13, on_delete=django.db.models.deletion.CASCADE, to='bibliography.Author'),
            preserve_default=False,
        ),
    ]
