# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-02 18:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bibliography', '0010_auto_20170224_2048'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='patronymic',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='author',
            name='pseudonym',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='bibliography',
            name='license',
            field=models.CharField(choices=[('private', 'Պաշտպանված է հեղինակային իրավունքով'), ('public', 'Հանրային սեփականություն')], default='public', max_length=20),
        ),
        migrations.AddField(
            model_name='text',
            name='text_name',
            field=models.CharField(blank=True, max_length=400, null=True),
        ),
        migrations.AlterField(
            model_name='press',
            name='link',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='press',
            name='number',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
