# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-04 09:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bibliography', '0011_auto_20170302_2218'),
    ]

    operations = [
        migrations.AlterField(
            model_name='press',
            name='number',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.RemoveField(
            model_name='text',
            name='author',
        ),
        migrations.AddField(
            model_name='text',
            name='author',
            field=models.ManyToManyField(blank=True, null=True, to='bibliography.Author'),
        ),
        migrations.RemoveField(
            model_name='textbook',
            name='author',
        ),
        migrations.AddField(
            model_name='textbook',
            name='author',
            field=models.ManyToManyField(to='bibliography.Author'),
        ),
    ]
