# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-05 07:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bibliography', '0012_auto_20170304_1349'),
    ]

    operations = [
        migrations.AddField(
            model_name='fiction',
            name='translation',
            field=models.ManyToManyField(to='bibliography.Author'),
        ),
    ]
