# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-06-25 20:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bibliography', '0014_bibliography_tokenized'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fiction',
            name='translation',
            field=models.ManyToManyField(blank=True, to='bibliography.Author'),
        ),
        migrations.AlterField(
            model_name='text',
            name='author',
            field=models.ManyToManyField(blank=True, to='bibliography.Author'),
        ),
    ]
